### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by Shadowfury22** [RedDot-3ND7355/BnS-Buddy#8] opened 2017-07-08 12:39 UTC
It happens everytime I try to login.

>System.NullReferenceException: Object reference not set to an instance of an object.
   on Revamped_BnS_Buddy.Form1.GrabToken()
   on System.Windows.Forms.Control.OnClick(EventArgs e)
   on System.Windows.Forms.Button.OnClick(EventArgs e)
   on System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   on System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   on System.Windows.Forms.Control.WndProc(Message& m)
   on System.Windows.Forms.ButtonBase.WndProc(Message& m)
   on System.Windows.Forms.Button.WndProc(Message& m)
   on System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Seems like you're missing a null check somewhere on the code you added for 5.8.7.4.

**Comment by RedDot-3ND7355** [comment] 2017-07-08 13:00
Did you try updating to 5.8.7.5?
Add me on Discord: 『Endless』#3967

**Comment by Shadowfury22** [comment] 2017-07-09 20:07
Yes, I did. Keeps crashing all the same. Whether I check "remember me" or not, the result is the same. I'll add you on discord tomorrow.

**Comment by RedDot-3ND7355** [comment] 2017-07-09 20:07
-link removed-
Try this version (temporary)

**Comment by Shadowfury22** [comment] 2017-07-09 21:53
It keeps crashing. But this time it shows an error message before the crash saying that "No available servers were found for NA/EU".

Edit: also, I don't know if it's relevant, but since 5.8.7.4 the program won't remember that my region is Europe and I have to change it everytime I open it (though maybe that's just because I've never been able to successfully connect since the bnsbuddy update).

**Comment by EverydayMayhem** [comment] 2017-07-10 17:00
Sorry  to barge in, I have the exact same problem, and downloading temporary version did the same thing (no available servers were found for NA/EU). 
And yes, remember me doesn't work for me too, and it always sets my server to Korean on the start.
P.S. OS Win7 x64

**Comment by RedDot-3ND7355** [comment] 2017-07-10 18:53
Guys,

here's a link for .3: https://cdn.discordapp.com/attachments/307411966677221376/333997638477414400/BnS_Buddy.exe
here's a link for .6(test): -link removed -
Please try .6 before .3 :)
~~~~~~~~~~~~~~~~~~~~
IF in .6 you get North America , Europe printed out in message boxes, then i might have figured out the problem :)
~~~~~~~~~~~~~~~~~~~~
remember is fixed in latest version ".5"
because previous version ".4" i messed up the check for the settings.ini wich would reset every time.
But now that .5 actually does it right.

Sign in/start game with remember me ticked on and everything should work just fine the next time you try to login.

**Comment by RedDot-3ND7355** [comment] 2017-07-10 18:56
In response to "EverydayMayhem"
If your server always goes to korean, that's because you have selected a korean game path.
Korean server only gets automatically selected IF it is installed and chosen as default path.

**Comment by EverydayMayhem** [comment] 2017-07-10 19:24
So I tried .6, the result is: first msg box: Servers not found for EU/NA, second msg box: Found NA, third: Found Europe and then goes .NET Framework msg box with details on the error (which was in the first post).
.3 though did nothing for me, it just starts BNS Buddy Updater, which says that I have currently 5.8.7.5 version. Did I do something wrong?

**Comment by RedDot-3ND7355** [comment] 2017-07-10 19:25
You can turn off the automatic updates in settings.ini
then use .3 again

**Comment by EverydayMayhem** [comment] 2017-07-10 19:28
Oh, I see. Now it runs just as it did before: .NET shows msg box with details on error, nothing else

**Comment by RedDot-3ND7355** [comment] 2017-07-10 19:30
The issue is not the latest update then

**Comment by EverydayMayhem** [comment] 2017-07-10 19:32
By the way, it does not select Korean server automatically now, it's just a blank space. The game placed in C:\Program Files (x86)\NCSOFT\BnS , so I don't know why did it select Korean server automatically, I didn't change the path or anything at all.

**Comment by RedDot-3ND7355** [comment] 2017-07-10 20:07
It only selects korean server if it's found in the nclauncher.ini file.
i did a couple fixes for that on later versions

**Comment by RedDot-3ND7355** [comment] 2017-07-11 13:21
Try this version: -link removed -
See if it fixes the play/login problem with this.
And also, is korean version of bns installed on your pc?

**Comment by EverydayMayhem** [comment] 2017-07-11 14:06
No, I don't have Korean version installed. And my gosh, it works with this version, finally. Thank you

**Comment by EverydayMayhem** [comment] 2017-07-11 14:18
Wow, uhm, don't know why, but my fps is terrible. When I use client without buddy it's around 50 to 60 in Jadestone village, and when I use buddy it's 20 max. When I used it around 2 or 3 month ago it was solid 60

**Comment by EverydayMayhem** [comment] 2017-07-11 14:22
Sorry, nvm, nvidia profile just screwed up for some reason. Sorry for inconvenience.
P.S. it does select europe now as it should

**Comment by RedDot-3ND7355** [comment] 2017-07-11 15:51
Glad to know this fixes it ^^
Thanks for testing!

**Closed as completed** 2021-12-06 01:12 UTC
Labels: Bug, Solved
